[package]
name = "typescape"
version = "0.0.1"
edition = "2021"
rust-version = "1.72.1"
license = "MIT"

[dependencies]
chumsky = "0.9.2"
serde-email = { version = "3.0.0", default-features = false }
thiserror = "1.0.49"
uuid = { version = "1.4.1", features = ["v4"] }

arbitrary = { version = "1.3.1", features = ["derive"], optional = true }
fake = { version = "2.8.0", optional = true }
lipsum = { version = "0.9.0", optional = true }
rand = { version = "0.8.5", optional = true }
serde = { version = "1.0.189", features = ["derive"], optional = true }

[dev-dependencies]
proptest = "1.3.1"
proptest-arbitrary-interop = "0.1.0"

[features]
default = ["internet"]
arbitrary = [ "dep:arbitrary", "dep:fake", "dep:rand", "dep:lipsum" ]
internet = []
serde = ["dep:serde", "uuid/serde"]
