[package]
name = "well-known"
version = "0.1.0"
edition = "2021"
rust-version = "1.73.0"

[dependencies]
arbitrary = { version = "1.3.1", features = ["derive"] }
check-if-email-exists = "0.9.1"
fake = "2.8.0"
rand = "0.8.5"
serde = { version = "1.0.189", features = ["derive"] }
thiserror = "1.0.49"

[dev-dependencies]
proptest = "1.3.1"
proptest-arbitrary-interop = "0.1.0"
