name: Build

on:
  push:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-audit
          restore-keys: ${{ runner.os }}-cargo-audit
      - run: which cargo-audit || cargo install cargo-audit
      - run: cargo audit
      - run: which cargo-deny || cargo install cargo-deny
      - run: cargo deny check

  check-clean:
    runs-on: ubuntu-latest
    needs: [audit]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - run: rustup component add clippy
      - run: cargo fmt -- --check
      - run: cargo check
      - run: cargo clippy --tests --benches -- --deny warnings

  check-full:
    runs-on: ubuntu-latest
    needs: [audit]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - run: rustup component add clippy
      - run: cargo fmt -- --check
      - run: cargo check --all-features
      - run: cargo clippy --all-features --tests --benches -- --deny warnings

  test:
    runs-on: ubuntu-latest
    needs: [check-full]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - run: which cargo-nextest || cargo install cargo-nextest
      - run: cargo nextest run --all-features
